import { Prefecture, PrefectureMapColumn } from '@/types/components';

export const prefectures: Prefecture[] = [
  { id: 1, name_en: 'Hokkaido', name_jp: '北海道' },
  { id: 2, name_en: 'Aomori', name_jp: '青森県' },
  { id: 3, name_en: 'Iwate', name_jp: '岩手県' },
  { id: 4, name_en: 'Miyagi', name_jp: '宮城県' },
  { id: 5, name_en: 'Akita', name_jp: '秋田県' },
  { id: 6, name_en: 'Yamagata', name_jp: '山形県' },
  { id: 7, name_en: 'Fukushima', name_jp: '福島県' },
  { id: 8, name_en: 'Ibaraki', name_jp: '茨城県' },
  { id: 9, name_en: 'Tochigi', name_jp: '栃木県' },
  { id: 10, name_en: 'Gunma', name_jp: '群馬県' },
  { id: 11, name_en: 'Saitama', name_jp: '埼玉県' },
  { id: 12, name_en: 'Chiba', name_jp: '千葉県' },
  { id: 13, name_en: 'Tokyo', name_jp: '東京都' },
  { id: 14, name_en: 'Kanagawa', name_jp: '神奈川県' },
  { id: 15, name_en: 'Niigata', name_jp: '新潟県' },
  { id: 16, name_en: 'Toyama', name_jp: '富山県' },
  { id: 17, name_en: 'Ishikawa', name_jp: '石川県' },
  { id: 18, name_en: 'Fukui', name_jp: '福井県' },
  { id: 19, name_en: 'Yamanashi', name_jp: '山梨県' },
  { id: 20, name_en: 'Nagano', name_jp: '長野県' },
  { id: 21, name_en: 'Gifu', name_jp: '岐阜県' },
  { id: 22, name_en: 'Shizuoka', name_jp: '静岡県' },
  { id: 23, name_en: 'Aichi', name_jp: '愛知県' },
  { id: 24, name_en: 'Mie', name_jp: '三重県' },
  { id: 25, name_en: 'Shiga', name_jp: '滋賀県' },
  { id: 26, name_en: 'Kyoto', name_jp: '京都府' },
  { id: 27, name_en: 'Osaka', name_jp: '大阪府' },
  { id: 28, name_en: 'Hyogo', name_jp: '兵庫県' },
  { id: 29, name_en: 'Nara', name_jp: '奈良県' },
  { id: 30, name_en: 'Wakayama', name_jp: '和歌山県' },
  { id: 31, name_en: 'Tottori', name_jp: '鳥取県' },
  { id: 32, name_en: 'Shimane', name_jp: '島根県' },
  { id: 33, name_en: 'Okayama', name_jp: '岡山県' },
  { id: 34, name_en: 'Hiroshima', name_jp: '広島県' },
  { id: 35, name_en: 'Yamaguchi', name_jp: '山口県' },
  { id: 36, name_en: 'Tokushima', name_jp: '徳島県' },
  { id: 37, name_en: 'Kagawa', name_jp: '香川県' },
  { id: 38, name_en: 'Ehime', name_jp: '愛媛県' },
  { id: 39, name_en: 'Kochi', name_jp: '高知県' },
  { id: 40, name_en: 'Fukuoka', name_jp: '福岡県' },
  { id: 41, name_en: 'Saga', name_jp: '佐賀県' },
  { id: 42, name_en: 'Nagasaki', name_jp: '長崎県' },
  { id: 43, name_en: 'Kumamoto', name_jp: '熊本県' },
  { id: 44, name_en: 'Oita', name_jp: '大分県' },
  { id: 45, name_en: 'Miyazaki', name_jp: '宮崎県' },
  { id: 46, name_en: 'Kagoshima', name_jp: '鹿児島県' },
  { id: 47, name_en: 'Okinawa', name_jp: '沖縄県' },
];

export const prefectureColumns: PrefectureMapColumn[] = [
  {
    name: 'tohoku',
    positions: ['Aomori', 'Iwate', 'Miyagi', 'Akita', 'Yamagata', 'Fukushima'],
    style: { right: '10%', bottom: '40%' },
  },
  {
    name: 'kanto',
    positions: ['Tokyo', 'Kanagawa', 'Saitama', 'Chiba', 'Ibaraki', 'Tochigi', 'Gunma'],
    style: { right: '20%', bottom: '5%' },
  },
  {
    name: 'hokkaido',
    positions: ['Hokkaido'],
    style: { right: '30%', bottom: '90%' },
  },
  {
    name: 'hokuriku',
    positions: ['Niigata', 'Toyama', 'Ishikawa', 'Fukui', 'Yamanashi', 'Nagano'],
    style: { right: '40%', bottom: '65%' },
  },
  {
    name: 'chubu',
    positions: ['Osaka', 'Shiga', 'Kyoto', 'Hyogo', 'Nara', 'Wakayama'],
    style: { right: '50%', bottom: '60%' },
  },
  {
    name: 'tokai',
    positions: ['Aichi', 'Gifu', 'Shizuoka', 'Mie'],
    style: { right: '30%', bottom: '10%' },
  },
  {
    name: 'shikoku',
    positions: ['Tokushima', 'Kagawa', 'Ehime', 'Kochi'],
    style: { right: '45%', bottom: '5%' },
  },
  {
    name: 'kyushu',
    positions: ['Fukuoka', 'Saga', 'Nagasaki', 'Kumamoto', 'Oita', 'Miyazaki', 'Kagoshima'],
    style: { right: '70%', bottom: '10%' },
  },
  {
    name: 'okinawa',
    positions: ['Okinawa'],
    style: { right: '70%', bottom: '80%' },
  },
  {
    name: 'chugoku',
    positions: ['Tottori', 'Shimane', 'Okayama', 'Hiroshima', 'Yamaguchi'],
    style: { right: '60%', bottom: '50%' },
  },
];